### ISSUE TITLE
Running with external DB

### ISSUE THREAD

**Issue by xthursdayx** [luzifer-docker/openfire#2]
Is there an easy way to run this with a more-robust external db (like Postgres), without having to fork and change the Dockerfile and/or `start.sh`?

I was also wondering if you know what each of the ports is used for? I'd be happy to fork your repo and create a PR with more complete docker installation documentation and descriptions of what the different ports and directories are used for, if that helps, but I'm a noob to openfire, so I'm exactly sure how everything works. 

Cheers.

**Comment by Luzifer** [comment]
Have a look at the setup assistant reachable on port 9090 (webinterface) of the container:
![image](https://user-images.githubusercontent.com/20142/130352684-06090592-c92a-4f38-a922-b7a2673a07f4.png)

List of ports: https://discourse.igniterealtime.org/t/list-of-ports-used-by-openfire/75860
